---
services:
  backend:
    build: 
      context: ./zile-filla-backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - EXPOSE_SUBTREE_ROOT=${EXPOSE_SUBTREE_ROOT}
    ports:
      - "8080:8080"
    volumes:
      - "C:\\custom-root:${EXPOSE_SUBTREE_ROOT}"
    command: ["mkdir", "${EXPOSE_SUBTREE_ROOT}"]
  
  client:
    build:
      context: ./zile-filla-web
      dockerfile: Dockerfile
    depends_on:
      - backend
    container_name: client
    environment:
      - BACKEND_HOST=backend
    ports:
      - "3000:3000"
