@startuml A2-view-file-content
title
Диаграмма деятельности просмотра содержимого текстового файла
Для FileReaderService 
end title

start
:Получить путь;
:Нормализовать путь;
:Сделать путь относительным для корневой директории;

if () then (Путь пустой)
    #pink: Исключение: не указан путь до файла;
    stop
endif

if () then (Это не путь до файла)
    #pink: Исключение: просмотреть можно только содержимое файла;
    stop
endif

if () then (Это не путь до текстового файла)
    #pink: Исключение: просмотреть можно только содержимое текстового файла;
    stop
endif

if () then (Это путь до не существующего файла)
    #pink: Исключение: файл не найден;
    stop
endif

#palegreen:Вернуть содержимое файла;
stop
@enduml