@startuml A3-delete-file-system-element
title
Диаграмма деятельности изменения удаления директории
end title

start
:Получить путь;
:Подставить в начало корневую директорию;
:Нормализовать путь;

if () then (Путь пустой)
    #pink: Исключение: нельзя удалить корневую директорию;
    stop
endif

if () then (Это путь до не существующей директории)
    #pink: Исключение: директория не найдена;
    stop
endif

#palegreen:Удалить указанную директорию;

stop

@enduml
