@startuml A4-rename-element
title
Диаграмма деятельности переименования элемента файловой системы
end title

start
:Получить путь;
:Подставить в начало корневую директорию;
:Нормализовать путь;

if () then (Путь пустой)
    #pink: Исключение: нельзя переименовать корневую директорию;
    stop
endif

if () then (Это путь до не существующего элемента)
    #pink: Исключение: элемент не найден;
    stop
endif

#palegreen:Переименовать указанный элемент;

stop

@enduml
