@startuml C1-file-metainf
title
Диаграмма классов метаинформации файлов и дириктори
end title

class File {
    size
    created
    modified
    opened
}

class Directory {
    size : recursive
    containedFilesAmount
    containedDirsAmount
    created
}
@enduml