@startuml C2-server

title
Концептуальная диаграмма классов серверной части Zile filla
end title

package zileFilla {
    allowmixing
    class ZileFilla {
        main(String ... args)
    }
    note right of ZileFilla : Точка входа в программу

    rectangle "some-configuration" as Configs
}

package fileSystemModule {
    class FileSystemController {
        changeDirectory(path)
    }
    note right of FileSystemController : Предоставляет методы взаимодействия\nс файловой системе

    class FileSystemService {
        changeDirectory(path)
    }
    note right of FileSystemService: Предоставляет доступ к файловой системе\nсогласно установленным ограничениям
}

package fileReaderModule {
    class FileReaderController {
        getFileContent(path)
    }
    note right of FileReaderController: Предоставляет методы для чтения\nсодержимого файлов

    class FileReaderService {
        getFileContent(path)
    }
    note right of FileReaderService: Предоставляет доступ к файловой системе\nсогласно установленным ограничениям
}

package filesystemAccessModule {
    class FileSystemApi {
        getMetaInformation(path)
        isFile(path)
        isDirectory(path)
        
    }
    note right of FileSystemApi: Предоставляет методы\nдля работы с файловой системой
}

ZileFilla ---> FileSystemController 
ZileFilla ---> FileReaderController  
ZileFilla -left-> Configs
FileSystemController --> FileSystemService
FileReaderController --> FileReaderService
FileSystemService ---> FileSystemApi
FileReaderService ---> FileSystemApi
@enduml