@startuml Change dir activity diagram
title
Диаграмма деятельности изменения текущей директории
Для класса FileSystemService
end title

start
:Получить путь;
:Сделать путь относительным для корневой директории;
:Нормализовать путь;

if () then (Путь пустой)
    #palegreen:Вернуть список дочерних элементов корневой директории\nс метаинформацией;
    stop
endif

if () then (Это не путь до директории)
    #pink: Исключение: перейти можно только в директорию;
    stop
endif

if () then (Это путь до не существующей директории)
    #pink: Исключение: директория не найдена;
    stop
endif

#palegreen:Вернуть список дочерних элементов указанной директории\nс метаинформацией;

stop

@enduml