@startuml Use case of Zile filla

title
Диаграмма прецедентов проекта Zile filla
end title

left to right direction

:Пользователь: as user
rectangle Обязательно {
    (Изменение текущей директории) -up- user
    (Посмотреть содержимое текстового файла) -up- user
    (Посмотреть метаинформацию о файле) -up- user
}

rectangle Бонус {
    (Удалить директорию или файл) -down- user
    (Переименовать директорию или файл) -down- user
    (Копировать директорию или файл) -down- user
    (Переместить директорию или файл) -down- user
    (Аутентифицироваться) -down- user
    (Загрузить файл на компьютер) -down- user
}


